# Generated by Django 5.0.7 on 2025-03-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='phase',
            field=models.CharField(max_length=255, unique=True, verbose_name='اسم المرحلة'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='eventtask',
            name='deadline',
        ),
        migrations.DeleteModel(
            name='Phase',
        ),
    ]
