# Generated by Django 5.0.7 on 2025-03-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_phase_remove_event_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='phase',
            field=models.CharField(max_length=255, verbose_name='اسم المرحلة'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('phase', 'name')},
        ),
    ]
